### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by ifdefdebug** [CristianT/LiteDBvsSQLite#1]
Hi,

Every single Insert in your loop actually triggers a begin -> insert -> commit sequence, and transactions "are atomic, consistent, isolated, and durable" [1] - so by forcing the engine to do a commit after every single insert you force the engine to guarantee the ACID state, involving a full sync to disc and everything else needed for ACID, one million times in a row.

In order to get a meaningful benchmark you would have to do something like this:

`db.Begin();
for(int i = 0; i < 1000000; i++) {
   /*insert*/
}
db.Commit();`

[1] https://sqlite.org/features.html

**Comment by CristianT** [comment]
It is a good observation, but the same is true in the test done in LiteBD while maintaining a much better performance. 

A separate analysis of batch inserts should be done to see the performance of that, but for me it has little value to insert 1M records in a batch.

**Comment by ifdefdebug** [comment]
If you have 1M records available beforehand, which is what happens in this benchmark, then there is no reason to not insert them in a single transaction. And in a real world scenario - like inserting one records at a time - LiteDB is going to cause a lot of work that you don't catch in your benchmark - specifically, a lot more syncing to disk, because it's clear from the numbers that LiteDB does not sync one million times.

To be clear: almost all of the time you are measuring for sqlite in this benchmark is spent by the engine sitting idle, between each two inserts, and waiting for the OS to finish a sync it asked for, that can't be skipped because you are running it in ACID mode, while LiteDB handles the data off to the OS and continues straight on.


So, those two benchmarks are not really comparable in a meaningful way if you instruct sqlite to be ACID for each insert and LiteDB not. To be fair, you should relax those requirements for sqlite so it can behave more like LiteDB (for instance `synchronous=off` [1] and journal_mode=WAL [2] - IIRC LiteDB has a WAL too).

[1] https://sqlite.org/pragma.html#pragma_synchronous
[2] https://sqlite.org/pragma.html#pragma_journal_mode
